# Generated by Django 3.0.3 on 2020-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0002_auto_20200220_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='metricTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_of_Editor', models.BooleanField()),
                ('Affiliation_of_Editor', models.BooleanField()),
                ('Number_of_Editors', models.BooleanField()),
                ('Review_Time', models.BooleanField()),
                ('Unclear_Review_Process', models.BooleanField()),
                ('Number_of_Paper_in_each_issue', models.BooleanField()),
                ('Questionable_special_issue', models.BooleanField()),
                ('Availablity_of_Journal_Full_Address', models.BooleanField()),
                ('Using_bogus_metric_and_index', models.BooleanField()),
                ('Send_journal_spam_Email_to_recieve_papers', models.BooleanField()),
                ('Fastrack_Fee', models.BooleanField()),
                ('Submission_Fee', models.BooleanField()),
                ('Publication_Fee', models.BooleanField()),
                ('Charging_both_authors_and_readers', models.BooleanField()),
            ],
        ),
    ]
