# Generated by Django 3.0.3 on 2020-02-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0003_metrictable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrictable',
            name='Affiliation_of_Editor',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Availablity_of_Journal_Full_Address',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Charging_both_authors_and_readers',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Email_of_Editor',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Fastrack_Fee',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Number_of_Editors',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Number_of_Paper_in_each_issue',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Publication_Fee',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Questionable_special_issue',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Review_Time',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Send_journal_spam_Email_to_recieve_papers',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Submission_Fee',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Unclear_Review_Process',
        ),
        migrations.RemoveField(
            model_name='metrictable',
            name='Using_bogus_metric_and_index',
        ),
        migrations.AddField(
            model_name='metrictable',
            name='abc',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
