# Generated by Django 3.0.3 on 2020-02-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0005_auto_20200225_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrictable',
            name='Affiliation_of_Editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Availablity_of_Journal_Full_Address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Charging_both_authors_and_readers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Email_of_Editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Fastrack_Fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Number_of_Editors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Number_of_Paper_in_each_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Publication_Fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Questionable_special_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Review_Time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Send_journal_spam_Email_to_recieve_papers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Submission_Fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Unclear_Review_Process',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrictable',
            name='Using_bogus_metric_and_index',
            field=models.BooleanField(default=False),
        ),
    ]
