# Generated by Django 3.0.3 on 2020-03-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0008_auto_20200228_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltable',
            name='Defined_aim_and_scope',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journaltable',
            name='Errorenous_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journaltable',
            name='Journal_relevance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journaltable',
            name='Listed_in_doaj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journaltable',
            name='Necessary_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journaltable',
            name='Transperancy',
            field=models.BooleanField(default=False),
        ),
    ]
