# Generated by Django 3.0.3 on 2020-03-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0011_auto_20200308_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable',
            name='Email_of_Editor',
            field=models.CharField(choices=[('official', '2'), ('gmail', '1'), ('not available', '0')], max_length=200),
        ),
    ]
