# Generated by Django 3.0.3 on 2020-03-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0013_auto_20200308_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable',
            name='Affiliation_of_Editor',
            field=models.CharField(choices=[('2', 'Full affiliation'), ('1', 'Only country name'), ('0', 'Not Available')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Email_of_Editor',
            field=models.CharField(choices=[('2', 'Official'), ('1', 'general Email Service'), ('0', 'Not Available')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Number_of_Editors',
            field=models.CharField(choices=[('2', 'Lower than 5'), ('1', 'Between 5-7'), ('0', 'More than 7')], max_length=200),
        ),
    ]
