# Generated by Django 3.0.3 on 2020-03-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0014_auto_20200308_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaltable',
            name='Availablity_of_Journal_Full_Address',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Charging_both_authors_and_readers',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Defined_aim_and_scope',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Errorenous_journal',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Fastrack_Fee',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Journal_relevance',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Listed_in_doaj',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Necessary_info',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Number_of_Paper_in_each_issue',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Publication_Fee',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Questionable_special_issue',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Review_Time',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Send_journal_spam_Email_to_recieve_papers',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Submission_Fee',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Transperancy',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Unclear_Review_Process',
        ),
        migrations.RemoveField(
            model_name='journaltable',
            name='Using_bogus_metric_and_index',
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Number_of_Editors',
            field=models.CharField(choices=[('2', 'More than 7'), ('1', 'Between 5-7'), ('0', 'Lower than 5')], max_length=200),
        ),
    ]
