# Generated by Django 3.0.3 on 2020-03-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0016_journaltable_to_be_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable',
            name='Number_of_Editors',
            field=models.CharField(choices=[('2', 'Official'), ('1', 'general Email Service'), ('0', 'Not Available')], max_length=200),
        ),
    ]
