# Generated by Django 3.0.3 on 2020-03-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0020_auto_20200309_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable',
            name='Number_of_Editors',
            field=models.CharField(choices=[('Using bogus metric or index', '-----'), ('2', 'No'), ('1', 'Yes')], max_length=200),
        ),
    ]
