# Generated by Django 3.0.3 on 2020-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0021_auto_20200309_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltable',
            name='Using_bogus_metric_and_index',
            field=models.CharField(choices=[('Using bogus metric or index', '-----'), ('2', 'No'), ('1', 'Yes')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Number_of_Editors',
            field=models.CharField(choices=[('Number of Editor', '-----'), ('2', 'More than 7'), ('1', 'Between 5-7'), ('0', 'Lower than 5')], max_length=200),
        ),
    ]
