# Generated by Django 3.0.3 on 2020-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0023_auto_20200309_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltable',
            name='Review_Time',
            field=models.CharField(choices=[('Review_Time', '-----'), ('2', 'More than a month'), ('1', 'Lower than a month'), ('0', 'Lower than a week')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
