# Generated by Django 3.0.3 on 2020-03-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0024_journaltable_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable',
            name='Affiliation_of_Editor',
            field=models.CharField(choices=[('Affiliation_of_Editor', '-----'), ('0', 'Full affiliation'), ('1', 'Only country name'), ('2', 'Not Available')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Email_of_Editor',
            field=models.CharField(choices=[('Email_of_Editor', '-----'), ('0', 'Official'), ('1', 'general Email Service'), ('2', 'Not Available')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Number_of_Editors',
            field=models.CharField(choices=[('Number_of_Editors', '-----'), ('0', 'More than 7'), ('1', 'Between 5-7'), ('2', 'Lower than 5')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Review_Time',
            field=models.CharField(choices=[('Review_Time', '-----'), ('0', 'More than a month'), ('1', 'Lower than a month'), ('2', 'Lower than a week')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journaltable',
            name='Using_bogus_metric_and_index',
            field=models.CharField(choices=[('Using_bogus_metric_and_index', '-----'), ('0', 'No'), ('1', 'Yes')], max_length=200),
        ),
    ]
