# Generated by Django 3.0.3 on 2020-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0027_auto_20200409_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable2',
            name='clarity_of_abstract_Regional_Journal',
            field=models.CharField(choices=[('clarity_of_abstract_Regional_Journal', '-----'), ('-2', 'No abstract'), ('-1', 'Abstract in Non Regional Language'), ('1', 'Abstract in Regional Language, fairly clear'), ('2', 'Abstract in Regional Language, very clear'), ('0', 'Not a regional journal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='journaltable2',
            name='review_time',
            field=models.CharField(choices=[('review_time', '-----'), ('-1', 'Lower than a week'), ('1', 'Lower than a month'), ('2', 'More than a month'), ('-2', ' Doesn’t mention ')], max_length=200),
        ),
    ]
