# Generated by Django 3.0.3 on 2020-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0028_auto_20200409_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaltable2',
            name='regional_language_homepage_availability_Regional_journal',
            field=models.CharField(choices=[('regional_language_homepage_availability_Regional_journal', '-----'), ('-2', 'not in reg lang'), ('-1', 'partially in reg lng'), ('1', 'entirely in reg lang'), ('0', 'journal not regional')], max_length=200),
        ),
    ]
