# Generated by Django 3.0.3 on 2020-04-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0030_addoptions_journal_options_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='new_option',
        ),
        migrations.DeleteModel(
            name='AddOptions',
        ),
    ]
