# Generated by Django 3.0.3 on 2020-04-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0031_auto_20200414_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pred.Options')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pred.Journal')),
                ('parameter', models.ManyToManyField(to='pred.Parameter')),
            ],
        ),
    ]
