# Generated by Django 3.0.3 on 2020-04-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0032_journaldatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaldatabase',
            old_name='Options',
            new_name='options',
        ),
    ]
