# Generated by Django 3.0.3 on 2020-04-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0033_auto_20200414_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaldatabase',
            name='parameter',
        ),
        migrations.AddField(
            model_name='journaldatabase',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pred.Parameter'),
            preserve_default=False,
        ),
    ]
