# Generated by Django 3.0.3 on 2020-04-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0034_auto_20200414_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaldatabase',
            old_name='options',
            new_name='chosen_option',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='journal',
        ),
        migrations.AddField(
            model_name='journal',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pred.Parameter'),
            preserve_default=False,
        ),
    ]
