# Generated by Django 3.0.3 on 2020-04-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0036_auto_20200414_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalDatabase',
        ),
    ]
