# Generated by Django 3.0.3 on 2020-04-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0037_delete_journaldatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='parameter',
        ),
    ]
